// src/app/data.ts
export const CLIENTS_DATA = [
  {
    name: 'John Doe',
    registered: '2023-01-01',
    role: 'Admin',
    status: 'Active',
  },
  {
    name: 'Jane Smith',
    registered: '2023-02-15',
    role: 'User',
    status: 'Inactive',
  },
  {
    name: 'Alice Johnson',
    registered: '2023-03-20',
    role: 'Manager',
    status: 'Pending',
  },
  {
    name: 'Bob Brown',
    registered: '2023-04-12',
    role: 'User',
    status: 'Active',
  },
  {
    name: 'Carol White',
    registered: '2023-05-03',
    role: 'Admin',
    status: 'Inactive',
  },
  {
    name: 'David Green',
    registered: '2023-06-21',
    role: 'Manager',
    status: 'Active',
  },
  {
    name: 'Eve Black',
    registered: '2023-07-10',
    role: 'User',
    status: 'Pending',
  },
  {
    name: 'Frank Blue',
    registered: '2023-08-25',
    role: 'Admin',
    status: 'Active',
  },
  {
    name: 'Grace Yellow',
    registered: '2023-09-02',
    role: 'User',
    status: 'Active',
  },
  {
    name: 'Hank Red',
    registered: '2023-10-18',
    role: 'Manager',
    status: 'Inactive',
  },
  {
    name: 'Ivy Grey',
    registered: '2023-11-05',
    role: 'User',
    status: 'Pending',
  },
  {
    name: 'Jack Silver',
    registered: '2023-12-01',
    role: 'Admin',
    status: 'Active',
  },
  {
    name: 'Karen Gold',
    registered: '2024-01-20',
    role: 'User',
    status: 'Inactive',
  },
  {
    name: 'Liam Bronze',
    registered: '2024-02-14',
    role: 'Manager',
    status: 'Active',
  },
  {
    name: 'Mona Steel',
    registered: '2024-03-01',
    role: 'Admin',
    status: 'Inactive',
  },
  {
    name: 'Nina Copper',
    registered: '2024-04-06',
    role: 'User',
    status: 'Pending',
  },
  {
    name: 'Oscar Zinc',
    registered: '2024-05-18',
    role: 'Manager',
    status: 'Active',
  },
  {
    name: 'Paul Platinum',
    registered: '2024-06-03',
    role: 'User',
    status: 'Active',
  },
  {
    name: 'Quincy Diamond',
    registered: '2024-07-12',
    role: 'Admin',
    status: 'Inactive',
  },
  {
    name: 'Rita Pearl',
    registered: '2024-08-22',
    role: 'User',
    status: 'Pending',
  },
  {
    name: 'Sam Emerald',
    registered: '2024-09-01',
    role: 'Manager',
    status: 'Active',
  },
  {
    name: 'Tina Ruby',
    registered: '2024-10-10',
    role: 'Admin',
    status: 'Inactive',
  },
  {
    name: 'Ursula Sapphire',
    registered: '2024-11-05',
    role: 'User',
    status: 'Pending',
  },
  {
    name: 'Victor Topaz',
    registered: '2024-12-15',
    role: 'Manager',
    status: 'Active',
  },
  {
    name: 'Wendy Opal',
    registered: '2024-01-28',
    role: 'Admin',
    status: 'Active',
  },
  {
    name: 'Xander Amethyst',
    registered: '2024-02-22',
    role: 'User',
    status: 'Inactive',
  },
  {
    name: 'Yara Aquamarine',
    registered: '2024-03-17',
    role: 'Manager',
    status: 'Active',
  },
  {
    name: 'Zane Onyx',
    registered: '2024-04-13',
    role: 'Admin',
    status: 'Inactive',
  },
  {
    name: 'Abigail Jade',
    registered: '2024-05-05',
    role: 'User',
    status: 'Pending',
  },
  {
    name: 'Ben Quartz',
    registered: '2024-06-18',
    role: 'Manager',
    status: 'Active',
  },
];
